### ISSUE TITLE
No IE11 support

### ISSUE THREAD

**Issue by Invictaz** [ltGuillaume/MusicFolderPlayer#14]
Does not work in IE11, however the other HTML5 based player does work. I don't get why.

https://github.com/GM-Script-Writer-62850/HTML5-Music-Player

**Comment by ltGuillaume** [comment]
There are so many simple JavaScript things not supported by IE11:
https://www.caniuse.com/#search=endswith
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/Default_parameters
etc. etc.

It's just not worth it to try to code for the really ancient browsers.

**Comment by Invictaz** [comment]
By all means but why is the other HTML5 player working then? It's just a music player. Not an advanced video decoding thing or VOIP app.

And IE11 is still supported upto 2020 with security updates, so I don't get the "ancient" tag.

**Comment by ltGuillaume** [comment]
Its JavaScript engine is. Pretty much anything else, too. The only reason it's still around is because Microsoft is too afraid that they'll lose enterprise customers that have web apps tailored for "good old" IE. Nobody else should use IE11, nobody. https://medium.com/@burger.neal/the-end-of-life-of-internet-explorer-11-12736f9ff75f The reason HTML5 Player apparently does work is because it doesn't use any of the newer JavaScript that breaks IE support. And just to be clear: MFP is written from scratch, it's not based on HTML5 Player; there are some concepts that I really liked about HTML5 Player, so I built on at.
