### ISSUE TITLE
Enhancement: Icons

### ISSUE THREAD

**Issue by OoLunar** [ltGuillaume/MusicFolderPlayer#17]
Make a config file of whether a person can enable or disable icons? Some people are complaining of how it's "annoying". They're picky, so don't take it personally.

**Comment by ltGuillaume** [comment]
Which icons are annoying? The icons used are all at the very bottom of `music.js` (the `:before` things), so you could change them yourself.

It's using [this font](https://zurb.com/playground/foundation-icon-fonts-3) (so you can download it there to see which codes are for which icon), or you can change fonts entirely.

If you find something that works better (if even for some), please let me see the result :)

Cheers!

**Comment by OoLunar** [comment]
Thank you! 
My viewers had said that [these](https://forsaken-borders.net/media/pictures/music_player_icons.png) icons "annoying" because it moves everything over a little bit. Normally I'd say tough it out, but they do *seem* a little extra. I'll leave it up to you personally, but keep up the good work!

**Comment by ltGuillaume** [comment]
Ah, ok. They're just indicating the function of that specific div. I think it's a playful way to do so (outside the div) and I don't see anything wrong with it, so I'll keep it in my version of what I concocted. It's totally cool if you remove them put them inside the div or whatever, of course. I would really appreciate it if you'd publish any changes made (as a fork), because 1) I'd like to see how variants of this turn out and 2) that's basically what GPL3 entails.

Cheers!

**Comment by OoLunar** [comment]
Will do! Have a good day.
