### ISSUE TITLE
Shuffle icon choice

### ISSUE THREAD

**Issue by GM-Script-Writer-62850** [ltGuillaume/MusicFolderPlayer#2]
the indicator for shuffle is either a dice, i would assume this means random, but i would also assume a check mark next to shuffle would mean random
the same can be said of Enqueue (yes, i copy/pasted that word)

**Comment by ltGuillaume** [comment]
Good point. Actually, it isn't a shuffle feature at all! I was thinking about this before. Shuffle would shuffle the playlist. The only this _this_ feature does is pick a random song from the library as soon as the playlist (which is actually more of a queue than a playlist, so I was thinking of refactoring that, too) has run its course. So, in my local version it already is refactored to "Random". The die as icon would then be just fine. (Full disclaimer: the font I used didn't contain a "shuffle" icon, so that's why I went for the die).

The check mark indicates that the feature is indeed enabled. That's a fine indication, not gonna change anything to that.

**Comment by GM-Script-Writer-62850** [comment]
Does it have a tool tip

**Comment by ltGuillaume** [comment]
Why? If the feature is enabled, there's a check mark next to it.

**Comment by GM-Script-Writer-62850** [comment]
To ensure there is no confusion
Just my opinion and thoughts/feedback

**Comment by ltGuillaume** [comment]
And it's immensely appreciated! :-) :-) I've also thought about having a background color between the almost-white of now and the :hover color to indicate if a feature is enabled. I just found it to be too distracting and not minimalistic enough, much like permanent use of coloring.

But now I finally realized what you actually meant. It's caused by the default values I set: `'random': (url.length == 1 ? true : false),`. My thinking was that if the entire library is loaded, it makes sense to enable Randomize by default, whereas when only a single folder is loaded, it's more likely you want to listen to that album in order. But that means that Randomize has a check mark in front of it by default and it indeed may confuse the user at first. Best is probably to take my assumption out of the equation altogether and set Randomize to false by default.

**Comment by GM-Script-Writer-62850** [comment]
"But now I finally realized what you actually meant.", You mean i got you thinking and you found something
you could do this:
https://codefisher.org/web_applications/css-tooltip/
i like to add some some css3 in there like fade in, shadows and rgba background like i did here:
https://github.com/GM-Script-Writer-62850/PHP-Scanner-Server

**Comment by ltGuillaume** [comment]
> You mean i got you thinking and you found something
No, I actually didn't understand :-P I think the confusion could only be because Randomize (previously Shuffle) was enabled by default, something I did later on. Either way, I'm satisfied by just setting Randomize to false by default.

About tooltips, I just use `title=` in the button elements, which works as a tooltip just fine.

**Comment by ltGuillaume** [comment]
Now it's a playlis, not just a a queue.
