### ISSUE TITLE
some ideas to improve the app

### ISSUE THREAD

**Issue by jranma** [ltGuillaume/MusicFolderPlayer#24]
this script is exactly what I was looking for: very simple (almost no install), no database, supports folders... thanks for the good work !

Here are some ideas to improve it: 

1. a "logout" link, to logout from HTTP auth
2. A longer music progress bar. On mobile, it's very short, no precision at all with big fingers !
3. support for image according to the song played
4. multiusers support: each user has access to his own music, playlists etc, and can share them to other user
5. share on: facebook, twitter buttons
6. I would suppress the 4 icons on the left, which I fond confusing and have no real value (was trying to click on the settings button)
7. ampache API support, so we can use apps to play music !

**Comment by ltGuillaume** [comment]
- Logout button should work [like this](https://github.com/ltGuillaume/MusicFolderPlayer/commit/21803cc59782da1c413be51ed5ac029479e020e4). There is no official way to do this, I found https://stackoverflow.com/questions/233507/how-to-log-out-user-from-web-site-using-basic-authentication to conjure up something, though. Chrome on Android may not play nice (does it ever?), let me know.
- Yeah I think this already is somewhat better in the [3.0 branch](https://github.com/ltGuillaume/MusicFolderPlayer/tree/3.0), but I'll check it out.
- I'll look into it https://github.com/ltGuillaume/MusicFolderPlayer/issues/23
- No, that's beyond the scope of MFP. It's not impossible, of course, because it's really easy to just run multiple copies of MFP in different folders. Sharing is covered.
- All that social media share stuff... not specific for each platform, definitely not gonna add that. Copy & paste is there already. What I might look into is a "generic share" button, so that (at least on Android), you can share it to any app that supports it).
- That's an esthetic thing, I like it the way it is.
- That is most definitely beyond the scope of MFP. Nevertheless, if you or someone you know could make that work, have at it! 😊

**Comment by jranma** [comment]
Regarding fb and twitter sharing buttons, they work the same way as your WhatsApp link..they are plateform independant. 
Salutations a la prochaine

**Comment by ltGuillaume** [comment]
> 
> 
> Regarding fb and twitter sharing buttons, they work the same way as your WhatsApp link..they are plateform independant.
> Salutations a la prochaine

So it's with a single URL, too, not with authentication & tokens, JSON shite and whatever?

**Comment by Chuck217** [comment]
I am loving MusicFolderPlayer -- Although I really have no use for the Sharing option -- Is there as easy way to disable it all together?

**Comment by ltGuillaume** [comment]
In `music.htm` you could replace
```
		<div id="shares">
```
with
```
		<div id="shares" style="display:none>
```

and in `music.js` remove
```
		case 83:	// s
			if (url.length > 1) return;
			dom.share.click();
			setFocus(dom.share);
			break;
```

**Comment by luiginobucosse** [comment]
Hi, thank you for your beautiful app. 
It would beautiful the option to change the sort order of the files: last modified, size, etc.

**Comment by ltGuillaume** [comment]
This repo still has a lot of catching up to do compared to the v3.x branch that I've been running for almost a year now.

The thing is, I'm not too interested in doing so until I find a way to get it working properly on mobile devices (see https://github.com/ltGuillaume/MusicFolderPlayer/issues/19).

**Comment by ltGuillaume** [comment]
@Chuck217 I just made the "Share" part in the interface optional in the [v3 branch](https://github.com/ltGuillaume/MusicFolderPlayer/tree/3.0): you can set `share = false` in the new configuration file `music.ini`. It will hide the Share button etc. and disable the keyboard shortcut.

**Comment by ltGuillaume** [comment]
> 5. share on: facebook, twitter buttons

@jranma Share dialog with several services that have a web share URL _and_ native share (via [Web Share API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share), supported on Android, iOS and partially on desktops) is coming up! The latter, of course, is most important, because it basically allows you to share to any app.

![image](https://user-images.githubusercontent.com/4777345/145737499-91ee01f0-8308-441f-94e0-5e3d04414be0.png)

**Comment by ltguillaume** [comment]
> > 5. share on: facebook, twitter buttons
> 
> @jranma Share dialog with several services that have a web share URL _and_ native share (via [Web Share API](https://developer.mozilla.org/en-US/docs/Web/API/Navigator/share), supported on Android, iOS and partially on desktops) is coming up! The latter, of course, is most important, because it basically allows you to share to any app.
> 
> ![image](https://user-images.githubusercontent.com/4777345/145737499-91ee01f0-8308-441f-94e0-5e3d04414be0.png)

Ouch, that took a while. Had been using this for so long already, but I never committed it to this repo... until last month. 🙈
