### ISSUE TITLE
Random playback & per-song volume

### ISSUE THREAD

**Issue by brantome** [ltGuillaume/MusicFolderPlayer#26]
Seems this function doesn't work on chrome.
I'm not sure what it is supposed to do: 
- change playlist order (list is shuffled on page load and songs are played in order according to this shuffled list) 
or 
- select random next song of the JSON playlist order (list is unchanged on page load). 

Either way, it does not work for me.

Another questions : how can I activate randomize and crossfade playlist functions by default ? And load a default playlist ? By default I mean for every new users.

Thank you for this great player

**Comment by brantome** [comment]
when I meant alphabetical, I should have said: the normal JSON playlist order (which in my case is alphabetical)

**Comment by brantome** [comment]
Another question: How can I activate randomize and crossfade playlist by default ?

**Comment by ltGuillaume** [comment]
It randomly picks a song from the playlist _below the currently playing song_. This way songs aren't played multiple times (like with any other shuffle implementation) and you can still see the order the songs were played in. It does work, but sometimes it just takes the next song below the currently playing.

You can manually change the default settings here: https://github.com/ltGuillaume/MusicFolderPlayer/blob/de188dbfd8f2d98602d6c46506ac0299b46b9713/music.js#L176

I will have to look into a separate configuration file with all the settings to accommodate user preferences and allow for easier updates...

**Comment by brantome** [comment]
Actually I tried many times and the randomize playlist function doesn't work at all for me. Could you by any chance send an example of it working ?

Here is my example. Try to load the playlist "test01.mfp.json" to see:


For the default playlist question, I updated "MusicFolderPlayer/music.js" and put playlist url like this:

'playlist': ['http://discobanana.club/musicFolderPlayer-auth-logout-button2/music.pls/test01.mfp.json'],

It is not working either.

**Comment by ltGuillaume** [comment]
Random works great here. But on line 642, you changed `Math.random()` to `Math.random(3)`. That probably broke it.

It has to be the playlist itself, not an url to the playlist... I took the contents of music.mfp.json and put in:
`'playlist': cfg.playlist = JSON.parse("[{\"path\":\"Budbringeren.mp3\",\"cover\":\"Budbringeren.jpg\",\"playNext\":1},{\"path\":\"DESIGN - The Minstrel's Theme 1971 (Psych-Pop).mp3\",\"cover\":\"Budbringeren.jpg\",\"playNext\":1},{\"path\":\"Denim Dance.mp3\",\"cover\":\"Denim Dance.jpg\",\"playNext\":1},{\"path\":\"Dino, Desi & Billy - Thru Spray Coloured Glasses.mp3\",\"cover\":\"Budbringeren.jpg\",\"playNext\":1},{\"path\":\"Domenic Troiano Band - The Outer Limits Of Soul.mp3\",\"cover\":\"Budbringeren.jpg\",\"playNext\":1},{\"path\":\"Elli Nevermind.mp3\",\"cover\":\"Budbringeren.jpg\",\"playNext\":1}]")`

**Comment by brantome** [comment]
I added the "3" in the js after I updated the thread yesterday. Sorry for confusion.

Without it, it is not working either. I removed the "3" in order for you to see.

Thank you for playlist, I will try it tonight.

**Comment by ltGuillaume** [comment]
Sry I made a mistake copying/pasting here, please remove `cfg.playlist = ` from the `'playlist':` code.

**Comment by brantome** [comment]
then it should be like this ?

`'playlist': JSON.parse("[{\"path\":\"Budbringeren.mp3\",\"cover\":\"Budbringeren.jpg\",\"playNext\":1},{\"path\":\"DESIGN - The Minstrel's Theme 1971 (Psych-Pop).mp3\",\"cover\":\"Budbringeren.jpg\",\"playNext\":1},{\"path\":\"Denim Dance.mp3\",\"cover\":\"Denim Dance.jpg\",\"playNext\":1},{\"path\":\"Dino, Desi & Billy - Thru Spray Coloured Glasses.mp3\",\"cover\":\"Budbringeren.jpg\",\"playNext\":1},{\"path\":\"Domenic Troiano Band - The Outer Limits Of Soul.mp3\",\"cover\":\"Budbringeren.jpg\",\"playNext\":1},{\"path\":\"Elli Nevermind.mp3\",\"cover\":\"Budbringeren.jpg\",\"playNext\":1}]"),`

Playlist doesn't appear when I load (and when the playlist was previously empty...

Thank you for your help

**Comment by ltGuillaume** [comment]
That's because your previous settings are remembered. You can either remove the local storage for the site from your browser, or open up the browser console (F12) when in your MFP instance, type in `cfg = null` (Enter), and refresh (F5).

About your playlist not being played back randomly: it's because you added the songs by right-clicking the song, thus forcing them to be played next (see `"playNext\":1`). This option is created to make sure that a song is actually played next, so the randomizing won't touch those songs. If you want to add songs to the playlist that should be randomized if Random is enabled, please enable "Enqueue" and then add the songs with a left-click.

**Comment by brantome** [comment]
Works fine. Very grateful for that. Althought I don't understand the randomize mode. What is the difference (in terms of shuffling) between:

- Load page with a randomized playlist and play it in order

and

- Load page with a randomized playlist and randomize again the remaining tracks when pressing next (your solution)

With the first solution, you also get to preserve the previously played tracks order, the same way your solution does. You may enlighten me on that (even if it doesn't bother me)

Also, I noticed that autoplay function doesn't respond everytime. At this time it is not responding at all. Is there any way to force chrome play MFP on load, besides the:

```
var
	autoplay = true,	
```

One very last question: can you think of a way to specify a volume per track (maybe as a JSON attribute or else) ? Every track would have a specified level (volume slider would not be visible in my player)

Many thanks for your help

**Comment by ltGuillaume** [comment]
Because if it's randomized at page load, then you cannot continue where you left off (after closing the browser/the next day/whatever). This is by far the best implementation of a playlist, I think, since it functions as both a playback log and a queue. You know exactly what songs are still to be played, and you can choose whether these songs will be played at random or in order. Songs can still be given preference via "Play next". Also, duplicate to-be-played songs won't be added, but you can also block already-played songs from being added again. If people add a whole bunch of songs of a single artist/album, they'll be randomized/shuffled with the other songs, but you can still see them together in the playlist, before they're being played.

Autoplay is mostly dependent on browser support. In Firefox it works perfectly, Chromium/Chrome is an enormous bitch in pretty much everything. Do you mean autoplay on a mobile device or a desktop browser? Which browser? Is autoplay definitely enabled?

Per-track volume is something I won't include. Since the player is built explicitly to _not_ have any kind of database, it doesn't make much sense to have such a feature. The only way I could think of is if you'd manually add it to the filename (e.g. `filename;.85.mp3` for a volume of .85) or manually edit a saved playlist to include volume as an attribute. Both ugly, I'd say 😊

**Comment by brantome** [comment]
Great random inplementation indeed! Now I get what you meant. Even if it is not really applicable to my example.

Let me tell a bit more about what I'd want:

- a fixed playlist (set up by me priorly) that will be loaded in shuffle order
- no functions at all on user-end. And I mean nothing, no player visible on the page. Just music playing randomly on page load with crossfade between tracks (thank god for that) and if possible a volume per track already fixed.

For this volume per track, you mentionned 

> manually edit a saved playlist to include volume as an attribute

That would be just perfect. But what would be the JSON attribute to specify for each track. Could you provide me an example ?

For autoplay, it is for a desktop browser first, no need for mobile... 

Chrome is used by so many people, I must have this autoplay working flawlessly on it, even if I agree with you: it is such a b****

Can't thank you more for your precious advices and work.

**Comment by ltGuillaume** [comment]
> a fixed playlist (set up by me priorly) that will be loaded in shuffle order

You can share a playlist directly, so you could have a look into that. That also takes a lot of functions out of the picture.

> no functions at all on user-end. And I mean nothing, no player visible on the page. Just music playing randomly on page load with crossfade between tracks (thank god for that) and if possible a volume per track already fixed.

Not sure if MFP is the best choice for you then, but you can always just remove the buttons and other elements you don't need from the music.htm file, or - probably better if you don't want to break anything - find their element id's in music.css and add `display: none`. It should be pretty straightforward.

As for volume, I guess you could add a check if there's a `volume` attribute, then set the volume accordingly, otherwise set the volume to `cfg.volume`.
In a playlist JSON, that would look like:
`{\"path\":\"Budbringeren.mp3\",\"cover\":\"Budbringeren.jpg\",\"volume\":.85}`

The reason the autoplay currently doesn't work in your instance is because you removed elements and the JavaScript is still trying to find them. So, it stops execution.

**Comment by brantome** [comment]
Yes I will use the display:none; css to hide player

As for volume per track, would you mind helping me with script ? I'm having a hard time doing this:

> As for volume, I guess you could add a check if there's a volume attribute, then set the volume accordingly, otherwise set the volume to cfg.volume.

I set the JSON as follow, in order to have different volume for each track:

`'playlist': JSON.parse("[{\"path\":\"01.mp3\",\"volume\":\".85\"},{\"path\":\"02.mp3\",\"volume\":\".25\"},{\"path\":\"03.mp3\",\"volume\":\".65\"},{\"path\":\"04.mp3\",\"volume\":\".15\"},{\"path\":\"05.mp3\,\"volume\":\".45\""},{\"path\":\"06.mp3\",\"volume\":\".95\"}]"),`

I think the value in `\"volume\":.85` requires a `\"` tag in order to work properly (otherwise page won't load).

As for the script, I am kind of lost...

That would be much appreciated.

test url: http://discobanana.club/psych60/music.htm

**Comment by ltGuillaume** [comment]
A proper way of creating a playlist with volume specification would be
```'playlist': JSON.parse("[{\"path\":\"01.mp3\",\"volume\":85},{\"path\":\"02.mp3\",\"volume\":25},{\"path\":\"03.mp3\",\"volume\":65},{\"path\":\"04.mp3\",\"volume\":15},{\"path\":\"05.mp3\",\"volume\":45},{\"path\":\"06.mp3\",\"volume\":95}]"),```

Note that I removed the need for the `.` in front, so see the value as percentage now.

The needed change in `music.js` can be found here: https://github.com/ltGuillaume/MusicFolderPlayer/commit/ea09b5e5d0f7cbe93690f4bea3a6ba96773acd4e

**Comment by ltGuillaume** [comment]
@brantome Hope you haven't moved away from MFP by now, it does work like you wanted now 😘

**Comment by brantome** [comment]
Hi,

No I didn't move away from MFP at all ;) I was travalling for a bit. I just came back. Is it possible to write to you by email? I would like to achieve the setup of my radio show... Can you see my email adress in github ?

**Comment by ltGuillaume** [comment]
@brantome Nope, can't see your email.

**Comment by brantome** [comment]
Ok. Can you write to me at francois.ledore@gmail.com please (if github displays it) ?

François
