### ISSUE TITLE
more filter options

### ISSUE THREAD

**Issue by Lykos4rchos** [ltGuillaume/MusicFolderPlayer#40]
Hey!

I was wondering if there is any way to have different categories for the filter, acting a little bit more like a Database. 
If the files have the details like BPM, date of release, Key and more... They can be displayed, allowing just to click on the category to sort tracks.

Will be very handy  :)

**Comment by ltGuillaume** [comment]
Hi! That is unfortunately far beyond the scope of the project. Metadata like that can only be made available by reading the ID3 tags and creating a database for this data.

The project is explicitly designed to not create a need for _any_ database to minimize setup procedure, the resources used and so that a simple F5 refresh will always present you with an up-to-date state of the library folder.

The only way MFP would be able to accommodate you in this is when you add the BMP (range), release date/year or key (range) to the filename itself, after which you can simply enter the desired value into the filter field. I'm sure there are many taggers who could do just that, if you want to explore such a setup.

Cheers!

**Comment by Lykos4rchos** [comment]
I understand. I was planning to build my database but realized it's too much resources for the final use I will have.
I will try my best scripting directly the filename as suggested.

Thanks you :)

**Comment by ltGuillaume** [comment]
Cool! If you did so using beets, let me know how it worked! 🙂 I'm still deciding on whether I'm going to use it myself, so successful examples could tip the scales 😉

**Comment by Lykos4rchos** [comment]
Hi!
I tried to use it, seems to be a very powerful tool. Unfortunately I haven't found the way to use it like I expect, feeling a little bit lost and not doing not even close results as hopped.

I found this library that could be easier to use https://pypi.org/project/mp3-tagger/
But i think I will finish be renaming in the "ugly" way because I also need to put everything together with BPM and Key detector (that i'm still searching for python).

My problem is that i'm not really confortable with web technologies but i know that with selenium and the library os I should be able to do everything.

I will still try lots of different things and if you want I'll notice you when I get stuff to work good enough :)

**Comment by ltGuillaume** [comment]
I just saw the BPM plugin documentation for beets and it seems you have to tap the beats on your keyboard yourself, lol 😬

So yeah, I guess you'd have to go through several processes with different tools to eventually get the desired result. Lemme know how you've solved it, perhaps I'll discover some new tools through that, too 🙂

**Comment by Lykos4rchos** [comment]
I'll try stuff till I find something working for me. 
I'll let you know if I have any updates

**Comment by Lykos4rchos** [comment]
Hey!
found _[this](https://github.com/mtg/essentia)_ and seems to be able to solve all my questions.
I'll give it a try 😃

**Comment by ltGuillaume** [comment]
Wow, impressive feature set. Even mood detection, so cool 😎
