### ISSUE TITLE
Search as you type + 1

### ISSUE THREAD

**Issue by qwertz098** [ltGuillaume/MusicFolderPlayer#45]
Hi ItGuillaume,

Great tool. I had two ideas addressing  my personal preferences. But maybe it's general enough or at least meets your interest.

May you be able to implement an optionally to activte search-as-you-type. Search seems fast enough for a reasonable user experience.

Could you add an option to deactivate the extra user interaction needed to add the whole folder to playlist by right/long click in folder view? 

Thx

**Comment by ltGuillaume** [comment]
I'm running instances of about 25953 songs, in that case it isn't quick enough. But I think I found a solid solution: start searching automatically only with a specified amount of characters in the input field (defined by the new setting `instantfilter` in `music.ini`). See latest commit.

As for deactivating the user interaction for adding folders... I don't think it's wise for mobile devices, because long-pressing might get triggered unintentionally, but otherwise you could just change the line

https://github.com/ltGuillaume/MusicFolderPlayer/blob/285df03d1e2201c07fcd8d5d0f394021e7217252/music.js#L393 to
```
if (true) {
```

**Comment by ltGuillaume** [comment]
@qwertz098 Errr just checking in. Does the current implentation work for you?

**Comment by qwertz098** [comment]
Thx Guillaume for the fast feedback, but unfortunately i wasn‘t able to check up to now. Trying to find some time soon! 

 

Von: Guillaume <notifications@github.com> 
Gesendet: Montag, 11. Januar 2021 22:51
An: ltGuillaume/MusicFolderPlayer <MusicFolderPlayer@noreply.github.com>
Cc: qwertz098 <kristian.krause@gmx.de>; Mention <mention@noreply.github.com>
Betreff: Re: [ltGuillaume/MusicFolderPlayer] Search as you type + 1 (#45)

 

@qwertz098 <https://github.com/qwertz098>  Errr just checking in. Does the current implentation work for you?

**Comment by ltGuillaume** [comment]
Cool! 👍
