### ISSUE TITLE
music.ini.template

### ISSUE THREAD

**Issue by jranma** [ltGuillaume/MusicFolderPlayer#47]
install procedure states that you must copy music.ini.template to music.ini and then configure music.ini
If you do so, and then delete "music.ini.template", website is not working anymore. 

template fil should be deleted without error, as it's only.. a template !

**Comment by ltGuillaume** [comment]
That's a good point. The idea was originally like that, but because changes in the configuration parameters would break the instance when updating, `music.ini.template` evolved into the place for the default settings. Therefore, my personal `music.ini` files now only contain the settings that differ from the defaults in `music.ini.template`, instead of a copy of the whole template.

So, we need to change that... What would be best? Change the name of `music.ini.template` to `musicdefaults.ini`? Or `musicdef.ini`?
